name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
    
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Check all targets
      run: cargo check --all --all-targets --all-features

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-A unknown_lints -D warnings"

    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Run cargo clippy
      run: cargo clippy --workspace --all-targets --all-features

  test:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all --all-features